# Databricks notebook source
# MAGIC %md
# MAGIC ## ICE_AAS.TBL_AAS_DEPLOYMENTS

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC DROP TABLE IF EXISTS ICE_AAS.TBL_AAS_DEPLOYMENTS;
# MAGIC
# MAGIC CREATE TABLE ICE_AAS.TBL_AAS_DEPLOYMENTS AS (
# MAGIC SELECT DISTINCT 
# MAGIC DC.claim_number,
# MAGIC TC.status_code,
# MAGIC TC.position_code,
# MAGIC CS.ClaimCreatedBy,
# MAGIC CS.ClaimCreatedTeam,
# MAGIC DC.CLAIM_ID,
# MAGIC CS.Workstream,
# MAGIC DC.Notification_Date,
# MAGIC DC.EVENT_DATE as AccidentDate,
# MAGIC DCUICL.CLAIM_NUMBER AS UICLClaimNumber,
# MAGIC DEP.DeployedBy,
# MAGIC DEP.DeployedByUsername,
# MAGIC DEP.DeployedByTeam,
# MAGIC
# MAGIC POLICYHOLDER.PARTY_ID AS Claimant_ID,
# MAGIC LTRIM(POLICYHOLDER.TITLE +  ' ' + POLICYHOLDER.FORENAME + ' ' + POLICYHOLDER.SURNAME) AS PHName,
# MAGIC DOV.registrationnumber,
# MAGIC DOV.vehicle_id,
# MAGIC DOV.VEHICLE_MAKE,
# MAGIC DOV.VEHICLE_MODEL,
# MAGIC DOV.IS_VEHICLE_DRIVEABLE,
# MAGIC DOV.repairable,
# MAGIC DOV.Total_Loss, 
# MAGIC DJOB.JOB_ID,
# MAGIC TJC.JOB_COMPONENT_ID,
# MAGIC DC.LIABILITY_DECISION,
# MAGIC DC.subrogated,
# MAGIC DCP.PARTY_ID,
# MAGIC DJOB.CNTCT_PARTY_ID,
# MAGIC TJOB.CLAIMANT_ID AS JOB_PARTY_ID, 
# MAGIC IFNULL(JOBPARTY.TITLE,'')+' '+IFNULL(JOBPARTY.FORENAME,'')+' '+IFNULL(JOBPARTY.SURNAME,'') AS PARTY_NAME,
# MAGIC DJOB.PARTY_TYPE,
# MAGIC DJOB.JOB_TYPE,
# MAGIC DJOB.JOB_SUB_TYPE_DESCRIPTION AS Milestone,
# MAGIC DJC.CHO_REFERENCE,
# MAGIC DJC.HIRE_CAT_DESCRIPTION,
# MAGIC DOV.REGISTRATIONNUMBEr as VEH_REG_NUM,
# MAGIC DSP.company_name,
# MAGIC company_reference,
# MAGIC
# MAGIC CASE WHEN COMPANY_NAME IN (
# MAGIC 'Accident Express Direct Ltd (Birmingham) Ltd',
# MAGIC 'Accident Express Ltd (Rugby) Ltd',
# MAGIC 'Alton Cars (Ashbourne) Ltd',
# MAGIC 'Alton Cars (Barnsley) Ltd',
# MAGIC 'Alton Cars (Doncaster) Ltd',
# MAGIC 'Alton Cars (High Peaks) Ltd',
# MAGIC 'Alton Cars (Harrogate) Ltd',
# MAGIC 'Alton Cars (Huddersfield) Ltd',
# MAGIC 'Alton Cars (Hull) Ltd',
# MAGIC 'Alton Cars (Leeds) Ltd',
# MAGIC 'Alton Cars (Mansfield) Ltd',
# MAGIC 'Alton Cars (Sheffield)',
# MAGIC 'Alton Cars (Sheffield )',
# MAGIC 'Alton Cars (York) Ltd',
# MAGIC 'Evans Halshaw Leeds',
# MAGIC 'Thompson Accident Repair (Carlisle)',
# MAGIC 'Pentagon ford Warrington',
# MAGIC 'Don Keeley Ltd',
# MAGIC 'Jim Clancy & Sons Ltd',
# MAGIC 'Lookers (Deeside)',
# MAGIC 'Lookers (Liverpool) Vauxhall',
# MAGIC 'Williams BMW Liverpool',
# MAGIC 'Williams BMW Stockport Bodyshop',
# MAGIC 'Fix Auto Manchester East',
# MAGIC 'Fletchers Accident Repair Centre Ltd',
# MAGIC 'HB Panelcraft',
# MAGIC 'Perfect Finish Ltd',
# MAGIC 'Steer Group Aston',
# MAGIC 'Steer Group Aylesbury',
# MAGIC 'Steer Group Birmingham',
# MAGIC 'Steer Group Brackley',
# MAGIC 'Steer Group Coventry',
# MAGIC 'Steer Group Corby',
# MAGIC 'Steer Group Leicester',
# MAGIC 'Steer Group Luton',
# MAGIC 'Steer Group Northampton',
# MAGIC 'Steer Group Stratford',
# MAGIC 'Steer Group Tamworth',
# MAGIC 'Steer Maidstone',
# MAGIC 'Steer Chatham',
# MAGIC 'Trust Ford Huddersfield',
# MAGIC 'Williams BMW Bolton Bodyshop',
# MAGIC 'Evans Halshaw Wolverhampton',
# MAGIC 'Hodson Ford',
# MAGIC 'Derek Walton',
# MAGIC 'Trust Ford Erdington',
# MAGIC 'Walmley Repair and Care',
# MAGIC 'Steer Birmingham',
# MAGIC 'Trust Ford Bradford',
# MAGIC 'Spraytone Ltd ',
# MAGIC 'Spraytone Ltd',
# MAGIC 'Lookers (Ellesmere Port)',
# MAGIC 'Drive Vauxhall Leamington Spa',
# MAGIC 'Baldwins Stratford',
# MAGIC 'Steer Group Stratford Upon Avon',
# MAGIC 'Steer Coventry ',
# MAGIC 'Steer Coventry',
# MAGIC 'AW Derby',
# MAGIC 'Burton Windscreens',
# MAGIC 'Bodykraft Dudley Ltd ',
# MAGIC 'Bodykraft Dudley Ltd',
# MAGIC 'Vertu Accident Repair Centre Harrogate',
# MAGIC 'Lookers (Speke)',
# MAGIC 'Williams BMW Liverpool Bodyshop',
# MAGIC 'Crossleys Accident Repair Centre Ltd',
# MAGIC 'Baldwins Leicester',
# MAGIC 'Turners Garage Leeds Ltd',
# MAGIC 'D Walton Ltd',
# MAGIC 'Vertu Accident Repair Centre Mansfield',
# MAGIC 'Autorestore Limited',
# MAGIC 'Steer Brackley',
# MAGIC 'Baldwins Corby',
# MAGIC 'Steer Corby',
# MAGIC 'Steer Northampton',
# MAGIC 'Trust Ford Warrington',
# MAGIC 'Trenhams Accident Repair Centre',
# MAGIC 'Turners Garage Ltd',
# MAGIC 'Turners Garage North YorkshireLtd',
# MAGIC 'Bodykraft Merry Hill Ltd',
# MAGIC 'Bodykraft Fastrack Ltd',
# MAGIC 'Evans Halshaw (Preston)',
# MAGIC 'Fletchers Accident Repair Centre',
# MAGIC 'Alton Cars ( HIgh Peak) Ltd',
# MAGIC 'Fix Auto Manchester East (Adamsons Crash Repair)',
# MAGIC 'Williams Manchester') AND TJC.SERVICEPROVIDER_JOB_COMP_TYPE = 'Motor Repair' THEN 'CCU1' 
# MAGIC
# MAGIC
# MAGIC WHEN COMPANY_NAME IN (
# MAGIC 'AFG Car Body Repairs',
# MAGIC 'Agmors Coachworks',
# MAGIC 'BPA Bodyshop',
# MAGIC 'Faraday Mill ARC',
# MAGIC 'ARC Bedford',
# MAGIC 'ARC Luton LLP',
# MAGIC 'ARC Daventry Ltd',
# MAGIC 'Graham Richardsons & Son Ltd',
# MAGIC 'Impact Accident Repairs Nottm Ltd',
# MAGIC 'Bedford Body Shop (BBS)',
# MAGIC 'Bennetts of Scotland (Ayr)',
# MAGIC 'Bennetts of Scoltand (Ayr)',
# MAGIC 'Bennetts Scotland (Ayr)',
# MAGIC 'Bennetts of Scotland (Edinburgh)',
# MAGIC 'Bennetts of Scotland (Glasgow)',
# MAGIC 'Brandon Body Centre',
# MAGIC 'North East Accident Repair Centre Darlington',
# MAGIC 'North East Accident Repair Centre Newcastle',
# MAGIC 'North East Accident Repair Centre Sunderland',
# MAGIC 'CF Motoring Services (Commercial)',
# MAGIC 'CF Motoring Services (Newcastle) Ltd',
# MAGIC 'CF Motoring Services (Sunderland) Ltd',
# MAGIC 'Cooper Barnes Ltd',
# MAGIC 'Burrwood Garage Ltd',
# MAGIC 'JR Accident Repair Centre Ltd',
# MAGIC 'Dicksons 2020 Ltd',
# MAGIC 'Drive Vauxhall Bristol North',
# MAGIC 'Drive Vauxhall Stockton',
# MAGIC 'Drive Vauxhall Darlington',
# MAGIC 'Drive Vauxhall Bury St Edmunds',
# MAGIC 'Drive Vauxhall Hartlepool',
# MAGIC 'Drive Vauxhall Leicester',
# MAGIC 'Drive Vauxhall Redcar',
# MAGIC 'Drive Vauxhall Weston Super Mare',
# MAGIC 'Evans Halshaw Gateshead',
# MAGIC 'Bridgend Accident Repair Centre Ltd',
# MAGIC 'D Cram Body Repairs Ltd',
# MAGIC 'Eastend Coachworks Ltd',
# MAGIC 'Faseko',
# MAGIC 'Fix Auto Loughborough',
# MAGIC 'Elder & Paton (Perth) Ltd',
# MAGIC 'GRM Bodycraft Ltd',
# MAGIC 'Kemnay Autobodies',
# MAGIC 'Paint Tec Fife',
# MAGIC 'Fraser Accident Repairs Ltd',
# MAGIC 'Parks Motor Group- Douglas Park Hillington',
# MAGIC 'Parks Motor Group- Douglas Park Sterling',
# MAGIC 'Parks Motor Group- Parks Inverness',
# MAGIC 'H Macartney Body Repairs',
# MAGIC 'Hall Graves Lee ARC',
# MAGIC 'Hammonds ARC',
# MAGIC 'Hartwell Ford Grimsby',
# MAGIC 'Hartwell Scunthorpe',
# MAGIC 'Parks Motor Group- Parks East Kilbride',
# MAGIC 'Protek (Bathgate) Ltd',
# MAGIC 'Leeder Accident Repair Centre',
# MAGIC 'Musselburgh Wagon Company Ltd',
# MAGIC 'Baylis Vauxhall (Cheltenham)',
# MAGIC 'Baylis (Gloucester) Ltd',
# MAGIC 'Edwards Ford',
# MAGIC 'English Ford',
# MAGIC 'Glastonbury Motor Body Repairs Ltd',
# MAGIC 'Yeovil Ford',
# MAGIC 'Andover Ford',
# MAGIC 'ARC Group (Bristol Accident Repair Centre)',
# MAGIC 'ARC Group (Chippenham Accident Repair Centre)',
# MAGIC 'ARC Group (Swindon Accident Repair Centre)',
# MAGIC 'Apollo Motor Company (Swindon) Ltd',
# MAGIC 'ARC Group (Weston Accident Repair Centre)',
# MAGIC 'Bristol Street Motors Gloucester Ford',
# MAGIC 'Fix Auto WSM',
# MAGIC 'Autocraft ARC (Aberystwyth)',
# MAGIC 'Evans Halshaw Merthyr',
# MAGIC 'Station Coachworks',
# MAGIC 'Fix Auto Owestry', 
# MAGIC 'Fordthorne',
# MAGIC 'Randall Howell Bodyshop',
# MAGIC 'Trenhams Wheels Limited',
# MAGIC 'RGM Vehicle Body Repairs Haverfordwest Ltd',
# MAGIC 'RGM Vehicle Body Repairs Swansea Ltd',
# MAGIC 'Turners Garage North Yorkshire Ltd',
# MAGIC 'Turners Garage Leeds',
# MAGIC 'Turners Garage Sheffield Ltd',
# MAGIC 'Apollo Motor Company (Bournemouth) Ltd',
# MAGIC 'Yell4Repairs',
# MAGIC 'Motofix Aldershot',
# MAGIC 'Motofix Cirencester',
# MAGIC 'Motofix Exeter',
# MAGIC 'Motofix High Wycombe',
# MAGIC 'Motofix Northampton',
# MAGIC 'Motofix Oxford',
# MAGIC 'Motofix Swindon',
# MAGIC 'Motofix Yeovil',
# MAGIC 'Vertu Accident Repair Centre Gloucester',
# MAGIC 'Vertu Accident Repair Centre Newcastle',
# MAGIC 'Vertu BMW Accident Repair Centre Sunderland',
# MAGIC 'Vertu Volkswagen Accident Repair Centre Nottingham',
# MAGIC 'Vertu Volkswagen Accident Repair Centre Harrogate',
# MAGIC 'Vertu Accident repair Centre Loughborough',
# MAGIC 'Vertu Volkswagen Accident Repair Centre Mansfield',
# MAGIC 'Peter James Group',
# MAGIC 'Fix Auto Bristol West',
# MAGIC 'Drive Vauxhall Bristol Central',
# MAGIC 'Trust Ford Bristol',
# MAGIC 'Cooper Barnes ',
# MAGIC 'Cooper Barnes',
# MAGIC 'Alfa Tail Lifts Ltd (Tail Gate Repairs Only)',
# MAGIC 'S & F Motors Ltd',
# MAGIC 'Lookers (Chelmsford)',
# MAGIC 'Lookers (Benfield)',
# MAGIC 'Lancaster Witham ',
# MAGIC 'Lancaster Witham',
# MAGIC 'Lancaster Witham.',
# MAGIC 'Faseko Limited',
# MAGIC 'AW Denaby (S Yorks)',
# MAGIC 'Bennetts Scotland (Edinburgh)',
# MAGIC 'Musselburgh Wagon Coachworks',
# MAGIC 'Protek Bathgate ',
# MAGIC 'Protek Bathgate',
# MAGIC 'GRM Bodycraft Limited',
# MAGIC 'Fix Auto Mid Devon',
# MAGIC 'Douglas Parks Stirling',
# MAGIC 'Evans Halshaw Glasgow',
# MAGIC 'Douglas Park Hillington',
# MAGIC 'Lookers (Lomond Audi)',
# MAGIC 'Bennetts Scotland (Glasgow)',
# MAGIC 'Douglas Park East Kilbride',
# MAGIC 'Motorbelle Accident Repair Centre Ltd',
# MAGIC 'Baldwins Aylesbury ',
# MAGIC 'Baldwins Aylesbury',
# MAGIC 'Steer Group Hayes',
# MAGIC 'Spraytech Aylesbury Ltd',
# MAGIC 'Hammond ARC',
# MAGIC 'East Bilney Coachworks (Thetford)',
# MAGIC 'MG Kerry Accident Repair Centre',
# MAGIC 'Douglas Park Inverness',
# MAGIC 'Dicksons Body Repair Centre',
# MAGIC 'QCD Automotive',
# MAGIC 'ARC Bedford Ltd ',
# MAGIC 'ARC Bedford Ltd',
# MAGIC 'Lookers (Carluke Accident Repair Centre)',
# MAGIC 'Evans Halshaw Bodycentre Gateshead',
# MAGIC 'Vertu Accident Repair Centre Newcastle',
# MAGIC 'CF Motoring Services (Blayden) Ltd',
# MAGIC 'Vertu Accident Repair Centre Sunderland',
# MAGIC 'AW Newark (Notts)',
# MAGIC 'AW Sleaford (Lincs)',
# MAGIC 'AW Nottingham',
# MAGIC 'D J Footitt',
# MAGIC 'West Somerset Motorsport Ltd',
# MAGIC 'The Windscreen Doctors',
# MAGIC 'Kemnay Autobodies Ltd',
# MAGIC 'Kemnay Autoboby Ltd',
# MAGIC 'AS Whitaker & Sons (Spalding)',
# MAGIC 'Autocraft ARC Ltd (Peterborough)',
# MAGIC 'AS Whitaker & Sons (Huntingdon)',
# MAGIC 'Advance Accident Repair',
# MAGIC 'AW Markham (Derys)',
# MAGIC 'Vertu Accident Repair Centre West Bridgford',
# MAGIC 'AW Boston',
# MAGIC 'Bristol Street Motors Sunderland',
# MAGIC 'AW Lincoln',
# MAGIC 'Evans Halshaw Manchester ') AND TJC.SERVICEPROVIDER_JOB_COMP_TYPE = 'Motor Repair' THEN 'CCU2'
# MAGIC
# MAGIC WHEN COMPANY_NAME IN (
# MAGIC 'Apollo Motor Company (Basingstoke) Ltd',
# MAGIC 'Apollo Motor Company (Bexhill) Ltd',
# MAGIC 'Fix Auto Penzance',
# MAGIC 'Apollo Motor Company (Cheltenham) Ltd',
# MAGIC 'Apollo Motor Company (Dover) Ltd',
# MAGIC 'Apollo Motor Company (Horsham) Ltd',
# MAGIC 'Highway Garage',
# MAGIC 'Apollo Motor Company (Portsmouth) Ltd',
# MAGIC 'Apollo Motor Company (Salisbury) Ltd',
# MAGIC 'Apollo Motor Company (Sittingbourne)',
# MAGIC 'Apollo Motor Company (Southampton) Ltd',
# MAGIC 'Apollo Motor Company (Tonbridge) Ltd',
# MAGIC 'Apollo Motor Company (Westbury)',
# MAGIC 'Apollo Motor Company (Yeovil)',
# MAGIC 'Apollo Prestige (Chichester) Ltd',
# MAGIC 'Allen Ford',
# MAGIC 'Auto Image London Ltd',
# MAGIC 'R S Dawe Ltd',
# MAGIC 'Trust Ford Dagenham',
# MAGIC 'Trust Ford Gillingham',
# MAGIC 'Body Management Repairs',
# MAGIC 'D&M Coachworks',
# MAGIC 'Brian Robson Coachworks',
# MAGIC 'C & D Services UK Ltd',
# MAGIC 'Caversham Coachworks Ltd',
# MAGIC 'Custom Coachworks',
# MAGIC 'Fix Auto Brighton',
# MAGIC 'Fix Auto Deepcut Garage', 
# MAGIC 'Fix Auto Hoddesdon',
# MAGIC 'Fix Auto Reading',
# MAGIC 'Grover ARC Ltd',
# MAGIC 'Thame Crash Repair Centre',
# MAGIC 'Wiltons of Shanklin Ltd',
# MAGIC 'JM Wadey Accident Repair',
# MAGIC 'Dinnages Garages Ltd',
# MAGIC 'RPM Body Shop Ltd',
# MAGIC 'T Reeve & Son Ltd',
# MAGIC 'Crowborough Accident Repair Services',
# MAGIC 'Manning and Boyce Accident Repairs Ltd',
# MAGIC 'Motorbelle Ltd',
# MAGIC 'Newbridge ARC Essex Ltd',
# MAGIC 'Newbridge ARC London Ltd',
# MAGIC 'Newbridge ARC Ltd',
# MAGIC 'Paramount Panel & Paint Ltd',
# MAGIC 'Southampton Accident Repairs',
# MAGIC 'Pauls Auto Repairs Ltd',
# MAGIC 'Premier Motors (solent) Ltd',
# MAGIC 'Rainbow Farnborough',
# MAGIC 'Rainbow Prestige',
# MAGIC 'Rainbow Reading',
# MAGIC 'Rainbow Slough',
# MAGIC 'Rainbow Wokingham',
# MAGIC 'Spraytech Aylesbury',
# MAGIC 'Tonbridge Accident Repair Centre',
# MAGIC 'Apollo Motor Company (Polegate) Ltd',
# MAGIC 'Autotech Smart Repairs Ltd',
# MAGIC 'Fix auto Mitcham',
# MAGIC 'Broadstairs Accident Repair',
# MAGIC 'Silverster', 
# MAGIC 'Bodyworks ARC',
# MAGIC 'Hartwell Bath',
# MAGIC 'Apollo Motor Company (Westbury) Ltd',
# MAGIC 'Fairlight Coachworks Ltd ',
# MAGIC 'Fairlight Coachworks Ltd',
# MAGIC 'Fix Auto Brighton Ta Frosts',
# MAGIC 'Spraytech Coachworks (Enfield)Ltd',
# MAGIC 'Lea Motors Ltd',
# MAGIC 'Drive Vauxhall Aldershot',
# MAGIC ' Motofix Aldershot',
# MAGIC 'Motofix Aldershot',
# MAGIC 'Silvester Coachworks',
# MAGIC 'Silvester Crash Repair',
# MAGIC 'Trust Ford Alperton',
# MAGIC 'Fix Auto Hainault',
# MAGIC 'Lookers (Maidstone) Mercedes ',
# MAGIC 'Lookers (Maidstone) Mercedes',
# MAGIC 'Steer Prestige Maidstone',
# MAGIC 'Invicta Body Repairs Ltd',
# MAGIC 'Evans Halshaw Bodycentre Gateshead',
# MAGIC 'Leeder Accident Repair Centre Ltd',
# MAGIC 'East Bilney Coachworks (Gorleston)',
# MAGIC 'East Bilney Coach Works (Norwich North)',
# MAGIC 'AWG Windscreens & Glazing Ltd',
# MAGIC 'Crowborough Coachworks',
# MAGIC 'Tonbridge Accident Repair Centre Ltd',
# MAGIC 'Baldwins London',
# MAGIC 'Apollo Motor Company (Sittingbourne) Ltd',
# MAGIC 'Brian Robson Coachworks Ltd',
# MAGIC 'Fix Auto Plymouth',
# MAGIC 'Evans Halshaw (Plymouth)',
# MAGIC 'Faraday Mill Accident Repair Centre',
# MAGIC 'Hall Graves Lee Accident Repair Centre',
# MAGIC 'Premier Motors Solent',
# MAGIC 'Reading Accident Repairs Ltd',
# MAGIC 'Rainbow Slough Xpress',
# MAGIC 'D&M Coachworks(Wandsworth)',
# MAGIC 'D & M Coachworks',
# MAGIC 'D&M Coachworks LTD',
# MAGIC 'Peter James Accident Repair',
# MAGIC 'Allen Ford (UK) Ltd',
# MAGIC 'Riverdale Body Repair Centre',
# MAGIC 'Fix Auto Wellington T/AWest Somerset Motorsport Ltd',
# MAGIC 'Lookers (Colchester)',
# MAGIC 'Total Body Shop Repairs Ltd',
# MAGIC 'Harold Wood Audi') AND TJC.SERVICEPROVIDER_JOB_COMP_TYPE = 'Motor Repair' THEN 'CCU3'
# MAGIC
# MAGIC WHEN NETWORK_APPROVED = 'NO' AND TJC.SERVICEPROVIDER_JOB_COMP_TYPE = 'MOTOR REPAIR' THEN 'NRRC'
# MAGIC WHEN TJC.SERVICEPROVIDER_JOB_COMP_TYPE <> 'MOTOR REPAIR' THEN NULL
# MAGIC ELSE 'OTHER' END AS RRCTeam,
# MAGIC
# MAGIC DSP.POSTCODE,
# MAGIC DSP.DAYTIME_PHONE,
# MAGIC DSP.EMAIL,
# MAGIC DSP.network_approved,
# MAGIC DJCS.job_component_status_description,
# MAGIC DJC.REFUSAL_RSN_DESCRIPTION,
# MAGIC REFUSEDBY.FULL_USERNAME AS RefusedBy,
# MAGIC REFUSEDBY.TEAM_DESCRIPTION AS RefusedByTeam,
# MAGIC CASE WHEN DSP.COMPANY_NAME IN ('AX LTD','HERTZ ACCIDENT SUPPORT') AND TJC.SERVICEPROVIDER_JOB_COMP_TYPE = 'MOTOR REPAIR' THEN 'CREDIT REPAIR' ELSE TJC.SERVICEPROVIDER_JOB_COMP_TYPE END AS JobCompType,
# MAGIC DJC.JOB_BASIS_DESCRIPTION,
# MAGIC DJC.TRACKN_ONLY_DESCRIPTION as TrackingOnly,
# MAGIC TJC.CURRENT_FLAG,
# MAGIC tjc.TRANSACTION_DATE as TransactionDate,
# MAGIC (SELECT TRANSACTION_DATE FROM hive_metastore.ice_aas.ice_trn_job_component WHERE JOB_COMPONENT_ID = TJC.JOB_COMPONENT_ID ORDER BY AUDIT_KEY ASC LIMIT 1) AS DateAdded,
# MAGIC DATE_FORMAT(TJC.DEPLOYED_DATE, 'yyyy-MM-dd') AS deployed_date,
# MAGIC DATE_FORMAT(TJC.ACCEPTED_DATE, 'yyyy-MM-dd') AS accepted_date,
# MAGIC DATE_FORMAT(TJC.VEHICLE_BOOKED_IN_DATE, 'yyyy-MM-dd') AS Booking_In_Date,
# MAGIC DATE_FORMAT(TJC.COMPLETION_ESTIMATED_DATE, 'yyyy-MM-dd') AS Esimated_Completion_Date,
# MAGIC DATE_FORMAT(TJC.REPAIR_AUTHORISED_DATE, 'yyyy-MM-dd') as Repair_Authorised_Date,
# MAGIC DATE_FORMAT(TJC.PARTS_ORDERED_DATE, 'yyyy-MM-dd') as Parts_Ordered_Date,
# MAGIC DATE_FORMAT(TJC.PARTS_DELIVERED_DATE, 'yyyy-MM-dd') as Parts_Delivered_Date,
# MAGIC DATE_FORMAT(TJC.WORK_STARTED_DATE, 'yyyy-MM-dd') AS work_started_date,
# MAGIC DATE_FORMAT(TJC.COMPLETED_DATE, 'yyyy-MM-dd') AS completed_date,
# MAGIC DATE_FORMAT(TJC.REFUSED_DATE, 'yyyy-MM-dd') AS Refused_Date,
# MAGIC
# MAGIC CASE 
# MAGIC WHEN TJC.SERVICEPROVIDER_JOB_COMP_TYPE = 'MOTOR REPAIR'
# MAGIC THEN DATEDIFF(DAY,WORK_STARTED_DATE,COMPLETED_DATE) END AS Repair_Days,
# MAGIC
# MAGIC CASE 
# MAGIC WHEN TJC.SERVICEPROVIDER_JOB_COMP_TYPE = 'HIRE CAR'
# MAGIC THEN DATEDIFF(DAY,TJC.WORK_STARTED_DATE,TJC.COMPLETED_DATE) END AS Days_of_Hire,
# MAGIC
# MAGIC DATE_FORMAT(TJC.VEHICLE_RETURNED_DATE, 'yyyy-MM-dd') AS Vehicle_Returned_Date,
# MAGIC DATE_FORMAT(TJC.VEHICLE_OFFERED_IN_DATE, 'yyyy-MM-dd') AS Vehicle_Offered_In_Date,
# MAGIC DJC.COURTESY_CAR_REQ_DESCRIPTION AS CourtesyCarRequired,
# MAGIC LATE_BKIN_RSN_DESCRIPTION as LateBookInReason,
# MAGIC HIREVEH.REGISTRATION_NUMBER AS HireReg,
# MAGIC HIREVEH.VEHICLE_MAKE as HireMake,
# MAGIC HIREVEH.VEHICLE_MODEL as HireModel,
# MAGIC THV.HIRE_CATEGORY_CODE as HireGTA
# MAGIC
# MAGIC
# MAGIC FROM hive_metastore.ice_aas.ice_trn_job_component TJC
# MAGIC
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_job DJOB ON TJC.JOB_ID = DJOB.JOB_ID  AND DJOB.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_trn_job TJOB ON TJC.JOB_ID = TJOB.JOB_ID AND TJOB.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_claim DC ON TJC.CLAIM_ID = DC.CLAIM_ID AND DC.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_trn_claim TC ON TC.CLAIM_ID = DC.CLAIM_ID AND TC.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_policy POLICY ON TC.POLICY_KEY = POLICY.POLICY_KEY AND POLICY.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_claim_party POLICYHOLDER ON TC.POLICYHOLDER_PARTY_ID = POLICYHOLDER.PARTY_ID AND POLICY.CURRENT_FLAG = 'Y'  AND POLICYHOLDER.CURRENT_FLAG = 'Y' 
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_claim_party JOBPARTY ON JOBPARTY.PARTY_ID = TJOB.CLAIMANT_ID AND JOBPARTY.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_job_component DJC ON TJC.JOB_COMPONENT_ID = DJC.JOB_COMPONENT_ID AND DJC.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_serviceprovider DSP  ON TJC.SERVICEPROVIDER_PARTY_KEY = DSP.SERVICEPROVIDER_KEY 
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_job_component_status DJCS ON TJC.JOB_COMPONENT_STATUS_ID = DJCS.JOB_COMPONENT_STATUS_ID
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_object_vehicle DOV ON TJC.VEHICLE_ID = DOV.VEHICLE_ID AND DOV.CURRENT_FLAG = 'Y' 
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_claim DCUICL ON DC.CLAIM_NUMBER = DCUICL.EXTERNAL_REFERENCE  AND DCUICL.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_trn_claim_party TCP ON DC.CLAIM_ID = TCP.CLAIM_ID AND TCP.CURRENT_FLAG = 'Y' AND TCP.NATURE = 'INSURER'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_claim_party DCP ON TCP.CLAIM_PARTY_ID = DCP.PARTY_ID AND DCP.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_trn_hire_vehicle THV ON THV.JOB_COMPONENT_ID = TJC.JOB_COMPONENT_ID AND THV.CURRENT_FLAG = 'Y'AND THV.FACT_EFFECTIVE_DATE IS NOT NULL
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_object_vehicle HIREVEH ON HIREVEH.VEHICLE_ID = THV.VEHICLE_ID AND HIREVEH.CURRENT_FLAG = 'Y'
# MAGIC LEFT JOIN hive_metastore.ice_aas.tbl_aas_claim_summary CS ON CS.CLAIM_ID = DC.CLAIM_ID 
# MAGIC
# MAGIC LEFT JOIN
# MAGIC (
# MAGIC SELECT * FROM
# MAGIC (
# MAGIC SELECT 
# MAGIC T.JOB_COMPONENT_ID,
# MAGIC DEPLOYEDUSER.FULL_USERNAME AS DeployedBy,
# MAGIC DEPLOYEDUSER.USERNAME AS DeployedByUsername,
# MAGIC DEPLOYEDUSER.TEAM_DESCRIPTION AS DeployedByTeam,
# MAGIC ROW_NUMBER() OVER (PARTITION BY T.JOB_COMPONENT_ID ORDER BY TRANSACTION_SEQ ASC) AS RN
# MAGIC FROM hive_metastore.ice_aas.ice_trn_job_component T 
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_user DEPLOYEDUSER ON T.PERFORMED_BY = DEPLOYEDUSER.USER_PARTY_ID
# MAGIC )MAIN WHERE RN=1
# MAGIC )DEP ON DEP.JOB_COMPONENT_ID=TJC.JOB_COMPONENT_ID
# MAGIC
# MAGIC LEFT JOIN
# MAGIC (
# MAGIC SELECT
# MAGIC TJC.claim_id,
# MAGIC TJC.job_id,
# MAGIC TJC.job_component_id,
# MAGIC refused_date,
# MAGIC REFUSAL_RSN_DESCRIPTION,
# MAGIC DU.FULL_USERNAME,
# MAGIC DU.TEAM_DESCRIPTION
# MAGIC FROM hive_metastore.ice_aas.ice_dim_job_component DJC
# MAGIC INNER JOIN  hive_metastore.ice_aas.ice_trn_job_component TJC ON DJC.JOB_COMPONENT_ID = TJC.JOB_COMPONENT_ID AND TJC.CURRENT_FLAG = 'Y' AND REFUSED_DATE IS NOT NULL
# MAGIC LEFT JOIN hive_metastore.ice_aas.ice_dim_user DU ON DU.USER_PARTY_ID = TJC.PERFORMED_BY
# MAGIC WHERE DJC.CURRENT_FLAG = 'Y'
# MAGIC ) REFUSEDBY ON REFUSEDBY.CLAIM_ID = TJC.CLAIM_ID AND REFUSEDBY.JOB_COMPONENT_ID = TJC.JOB_COMPONENT_ID
# MAGIC
# MAGIC WHERE TJC.CURRENT_FLAG = 'Y' 
# MAGIC
# MAGIC )
# MAGIC
