# Databricks notebook source
# MAGIC %md
# MAGIC ## ICE_AAS.TBL_AAS_THIRD_PARTIES

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS ICE_AAS.TBL_AAS_THIRD_PARTIES;
# MAGIC
# MAGIC CREATE TABLE ICE_AAS.TBL_AAS_THIRD_PARTIES
# MAGIC AS (
# MAGIC
# MAGIC SELECT DISTINCT
# MAGIC ROW_NUMBER () OVER (PARTITION BY TCP.CLAIM_ID ORDER BY PARTY_ID ASC) AS TPNumber,
# MAGIC TCP.CLAIM_ID,
# MAGIC DC.CLAIM_NUMBER,
# MAGIC PARTY_ID,
# MAGIC DOV.REGISTRATIONNUMBER,
# MAGIC dov.VEHICLE_MAKE,
# MAGIC dov.VEHICLE_MODEL,
# MAGIC dov.IS_VEHICLE_DRIVEABLE,
# MAGIC dov.CURRENT_VEH_LOC_DESCRIPTION,
# MAGIC DC.TP_INSURER,
# MAGIC CASE 
# MAGIC WHEN TPI.ORGANISATION_NAME IS NULL THEN DC.TP_INSURER ELSE TPI.ORGANISATION_NAME END AS ORGANISATION_NAME,
# MAGIC TPI.PARTYTYPE_CODE,
# MAGIC TPIPostalAddress,
# MAGIC CORRESPONDENCE_ADDRESS,
# MAGIC INSPOLICYNUM,
# MAGIC insclaimnum as TPCLAIMNUM,
# MAGIC DCP.LIABILITY_PERCENTAGE,
# MAGIC TITLE,
# MAGIC FORENAME,
# MAGIC SURNAME,
# MAGIC dcp.ORGANISATION_NAME AS CompanyName,
# MAGIC dcp.POSTAL_ADDRESS,
# MAGIC POSTCODE,
# MAGIC EMAIL,
# MAGIC DAYTIME_PHONE,
# MAGIC EVENING_PHONE,
# MAGIC MOBILE,
# MAGIC VAT_STATUS,
# MAGIC DCP.CURRENT_FLAG
# MAGIC
# MAGIC
# MAGIC FROM ice_aas.ice_dim_claim_party DCP
# MAGIC
# MAGIC INNER JOIN ice_aas.ice_trn_claim_party TCP ON DCP.PARTY_ID = TCP.CLAIM_PARTY_ID AND TCP.CURRENT_FLAG = 'Y' AND NATURE = 'THIRD_PARTY' AND CLAIMANT_IND  = 'YES' AND PASSENGER_IND = 'NO' 
# MAGIC   
# MAGIC LEFT JOIN ice_aas.ice_dim_object_vehicle DOV ON TCP.VEHICLE_ID = DOV.VEHICLE_ID AND DOV.CURRENT_FLAG = 'Y'
# MAGIC
# MAGIC INNER JOIN ice_aas.ice_dim_claim DC ON TCP.CLAIM_ID = DC.CLAIM_ID AND DC.CURRENT_FLAG = 'Y'
# MAGIC
# MAGIC   LEFT JOIN 
# MAGIC   (
# MAGIC   SELECT DISTINCT
# MAGIC   ROW_NUMBER () OVER (PARTITION BY CLAIM_ID ORDER BY EFF_START desc) AS TPINumber,
# MAGIC 	tstamp,
# MAGIC   CLAIM_ID,
# MAGIC 	TPP.PARENT_PARTY_ID,
# MAGIC 	TPP.CHILD_PARTY_ID,
# MAGIC 	DCP.ORGANISATION_NAME,
# MAGIC 	DCP.PARTYTYPE_CODE,
# MAGIC 	dcp.POSTAL_ADDRESS+''+dcp.POSTCODE as TPIPostalAddress,
# MAGIC 	TPP.CURRENT_FLAG
# MAGIC 	
# MAGIC   FROM ice_aas.ice_trn_party_party TPP
# MAGIC   INNER JOIN ice_aas.ice_dim_claim_party DCP ON DCP.PARTY_ID = TPP.CHILD_PARTY_ID AND DCP.CURRENT_FLAG = 'Y'
# MAGIC
# MAGIC   WHERE TPP.CURRENT_FLAG = 'Y' AND nature = 'THIRD_PARTY_INSURER'
# MAGIC
# MAGIC   ) TPI ON DCP.PARTY_ID = TPI.PARENT_PARTY_ID AND TPINUMBER = 1
# MAGIC
# MAGIC 	where DCP.CURRENT_FLAG = 'Y'  
# MAGIC
# MAGIC   ORDER BY CLAIM_ID ASC 
# MAGIC )
