# Databricks notebook source
# MAGIC %md
# MAGIC ## ICE_AAS.TBL_AAS_INVOICES

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC DROP TABLE IF EXISTS ICE_AAS.TBL_AAS_INVOICES;
# MAGIC
# MAGIC CREATE TABLE ICE_AAS.TBL_AAS_INVOICES AS (
# MAGIC
# MAGIC select
# MAGIC DISTINCT
# MAGIC DC.CLAIM_ID,
# MAGIC DC.CLAIM_NUMBER,
# MAGIC dc.SUBROGATED,
# MAGIC TI.JOB_ID,
# MAGIC TI.JOB_COMPONENT_ID,
# MAGIC
# MAGIC DI.INVOICE_ID,
# MAGIC DI.Invoice_number,
# MAGIC TI.invoice_to_id,
# MAGIC CASE 
# MAGIC WHEN INVTO.PARTYTYPE_CODE = 'INSURER' THEN INVTO.ORGANISATION_NAME
# MAGIC WHEN INVTO.PARTYTYPE_CODE = 'DRIVER' then INVTO.TITLE+' '+INVTO.FORENAME+' '+INVTO.SURNAME
# MAGIC WHEN INVTO.PARTYTYPE_CODE = 'PERSON' then INVTO.TITLE+' '+INVTO.FORENAME+' '+INVTO.SURNAME
# MAGIC WHEN INVTO.PARTYTYPE_CODE = 'ORGANISATION' THEN INVTO.ORGANISATION_NAME
# MAGIC WHEN INVTO.PARTYTYPE_CODE = 'COMPANY' THEN INVTO.companyname end AS InvoiceTo,
# MAGIC dc.NOTIFICATION_DATE,
# MAGIC TI.INVOICE_DATE,
# MAGIC
# MAGIC ledger_type,
# MAGIC invoice_type,
# MAGIC --DI.REFERENCE,
# MAGIC DI.STATUS,
# MAGIC
# MAGIC dic.invoice_category_description,
# MAGIC ti.GTA_DAILY_UPLIFT_RATE_AMT,
# MAGIC DP.TRANS_CODE_DESCRIPTION,
# MAGIC DP.TRANSACTION_REASON,
# MAGIC DCP.ORGANISATION_NAME AS Party,
# MAGIC CHARGE_TYPE_CODE,
# MAGIC sum(ti.NETT_AMT) as NettAmount,
# MAGIC sum(ti.VAT_AMT) AS VAT_AMT,
# MAGIC sum(ti.GROSS_AMT) AS GrossAmount,
# MAGIC SUM(TI.invoice_total_due_amt) AS TotalAmountDue,
# MAGIC DP.CHEQUE_RUN_DATE,
# MAGIC TI.TRANSACTION_DATE,
# MAGIC DP.PAYMENT_METHOD,
# MAGIC DP.PAYEE_REFERENCE,
# MAGIC DP.PAYEE,
# MAGIC
# MAGIC us.FULL_USERNAME,
# MAGIC SUM(CASE WHEN CHARGE_TYPE_CODE = 'TOTAL_LOSS' THEN ti.GROSS_AMT end) AS T_LCost,
# MAGIC SUM(CASE WHEN CHARGE_TYPE_CODE IN ('OTHERFEES','REPAIR') THEN  ti.GROSS_AMT END) AS RepairCost,
# MAGIC SUM(CASE WHEN CHARGE_TYPE_CODE = 'HIRE_CAR' THEN  ti.GROSS_AMT END) AS HireCost,
# MAGIC
# MAGIC SUM(CASE WHEN CHARGE_TYPE_CODE = 'TOW_FEE' THEN  ti.GROSS_AMT END) AS TowCost
# MAGIC
# MAGIC
# MAGIC
# MAGIC
# MAGIC
# MAGIC   FROM hive_metastore.ice_aas.ice_trn_invoice TI
# MAGIC
# MAGIC
# MAGIC
# MAGIC
# MAGIC   INNER JOIN hive_metastore.ice_aas.ice_dim_invoice DI ON TI.INVOICE_ID = DI.INVOICE_ID and di.CURRENT_FLAG = 'Y'
# MAGIC   INNER JOIN hive_metastore.ice_aas.ice_dim_claim DC ON TI.claim_id = DC.claim_id and dc.current_flag = 'Y'
# MAGIC   LEFT JOIN hive_metastore.ice_aas.ice_dim_claim_party DCP ON TI.serviceprovider_party_id = DCP.PARTY_ID and dcp.current_flag = 'Y'
# MAGIC   LEFT JOIN hive_metastore.ice_aas.ice_dim_invoice_category DIC ON TI.invoice_category_id = dic.invoice_category_id and dic.CURRENT_FLAG ='Y'
# MAGIC   LEFT JOIN hive_metastore.ice_aas.ice_dim_claim_party INVTO ON INVTO.PARTY_ID = TI.invoice_to_id AND INVTO.CURRENT_FLAG = 'Y'
# MAGIC   
# MAGIC   LEFT JOIN 
# MAGIC   --LEFT JOIN dbo.EXP_DIM_PAYMENT DP ON DI.INVOICE_ID = DP.INVOICE_ID and DP.CURRENT_FLAG = 'Y'
# MAGIC   
# MAGIC   (
# MAGIC   select
# MAGIC   job_id,
# MAGIC   invoice_id,
# MAGIC   max(payment_method) As payment_method,
# MAGIC   max(payee_reference) AS payee_reference,
# MAGIC   max(cheque_run_Date) As Cheque_Run_Date,
# MAGIC   MAX(TRANS_CODE_DESCRIPTION) AS TRANS_CODE_DESCRIPTION,
# MAGIC   MAX(TRANSACTION_REASON) AS TRANSACTION_REASON ,
# MAGIC   MAX(PAYEE) AS PAYEE
# MAGIC   from hive_metastore.ice_aas.tbl_aas_payments
# MAGIC   where current_flag = 'Y'
# MAGIC   group by 
# MAGIC   job_id,
# MAGIC   invoice_id
# MAGIC   )  DP ON TI.JOB_ID = DP.JOB_ID AND TI.INVOICE_ID = DP.INVOICE_ID
# MAGIC
# MAGIC   LEFT JOIN hive_metastore.ice_aas.ice_dim_user US on TI.PERFORMED_BY_PARTY_KEY = US.USER_KEY
# MAGIC   LEFT JOIN hive_metastore.ice_aas.ice_dim_charge_type CT ON TI.CHARGE_TYPE_ID = CT.CHARGE_TYPE_ID AND CT.CURRENT_FLAG = 'Y'
# MAGIC   where TI.CURRENT_FLAG = 'Y' and TI.invoice_line_effective = 'Y'
# MAGIC
# MAGIC   group by
# MAGIC   DC.CLAIM_ID,
# MAGIC DC.CLAIM_NUMBER,
# MAGIC dc.SUBROGATED,
# MAGIC TI.JOB_ID,
# MAGIC TI.JOB_COMPONENT_ID,
# MAGIC DI.Invoice_number,
# MAGIC DI.Invoice_ID,
# MAGIC TI.invoice_to_id,
# MAGIC INVTO.ORGANISATION_NAME,
# MAGIC dc.NOTIFICATION_DATE,
# MAGIC TI.INVOICE_DATE,
# MAGIC ledger_type,
# MAGIC invoice_type,
# MAGIC --DI.REFERENCE,
# MAGIC DI.STATUS,
# MAGIC CHARGE_TYPE_CODE,
# MAGIC dic.invoice_category_description,
# MAGIC ti.GTA_DAILY_UPLIFT_RATE_AMT,
# MAGIC dcp.ORGANISATION_NAME,
# MAGIC DP.CHEQUE_RUN_DATE,
# MAGIC DP.TRANS_CODE_DESCRIPTION,
# MAGIC DP.TRANSACTION_REASON,
# MAGIC DP.PAYEE,
# MAGIC DP.PAYMENT_METHOD,
# MAGIC DP.PAYEE_REFERENCE,
# MAGIC TI.TRANSACTION_DATE,
# MAGIC us.FULL_USERNAME,
# MAGIC INVTO.TITLE,
# MAGIC INVTO.FORENAME,
# MAGIC INVTO.SURNAME,
# MAGIC INVTO.companyname,
# MAGIC INVTO.PARTYTYPE_CODE
# MAGIC )
# MAGIC  
# MAGIC
# MAGIC
# MAGIC
